### ISSUE TITLE
json results type

### ISSUE THREAD

**Issue by drewp** [tomayac/ldf-client#2]
ldf-query-polling-response and ldf-query-streaming-response-partial return json strings, and ldf-query-streaming-response-end returns a bunch of rows, each as json, concatenated together. 

I can't see how anyone would use that concatenated json, so maybe it's better to save time and memory to not collect it.

More importantly, why jsonify the rows for the other events? All callers will just have to parse them. The demo code doesn't even seem to be expecting that json, as it calls JSON.stringify on the e.detail.response strings as if they were row objects.

**Comment by tomayac** [comment]
I simply wrap @RubenVerborgh's [browser.js](https://github.com/LinkedDataFragments/jQuery-Widget.js). Ruben, what is your reaction to Drew's remarks above? I guess I am a couple of builds behind and missed the repo rename apparently…

**Comment by RubenVerborgh** [comment]
Well, the  `data` callback [here](https://github.com/tomayac/ldf-client/blob/v0.0.3/ldf-client.html#L89-L95) receives a row object or a triple (which is perhaps misleading called `chunk` here). So basically, by removing the `JSON.stringify` instances, you can pass the raw JSON object.

About the renaming: the old Browser.js project had the browser version of Client.js. However, we have now changed this. The new [Client.js](https://github.com/LinkedDataFragments/Client.js) is its own browser version which you can generate through browserify. The new [https://github.com/LinkedDataFragments/jQuery-Widget.js](jQuery-Widget.js) is now a jQuery widget that uses the browserified code. I've added [instructions on how to generate a browserified version easily](https://github.com/LinkedDataFragments/Client.js/tree/develop#browser-version).

**Comment by tomayac** [comment]
@RubenVerborgh, shall we discuss the migration path to the latest version of `jQuery-Widget.js` over a quick VC (calendar week 38 would work, traveling this week)?

**Comment by RubenVerborgh** [comment]
@tomayac It should come down to simply updating `dependencies/ldf-client-browser.js` to the `ldf-client-browser.js` which is now generated by Client.js (you wouldn't need jQuery-Widget.js). But we sure can do a VC, ping we when you're available.
